/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Image;
import java.io.*;
import java.net.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.*;
/**
 *
 * @author HP
 */
public class CekCuacaSederhanaFrame extends javax.swing.JFrame {
    private static final String API_KEY = "dd07a5aaf16a778da36817495e8a09b2";
    /**
     * Creates new form CekCuacaSederhanaFrame
     */
    public CekCuacaSederhanaFrame() {
    initComponents();
    
    // 🔹 Muat daftar kota favorit dari file
    muatKotaFavorit();

    // 🔹 Tambahkan listener: saat user memilih dari combo box, isi ke TxtKota
    CbxLokasi.addActionListener(e -> {
        String kotaDipilih = (String) CbxLokasi.getSelectedItem();
        if (kotaDipilih != null && !kotaDipilih.equals("Pilih Kota")) {
            TxtKota.setText(kotaDipilih);
        }
    });
    TxtKota.setText("");
    LblCuaca.setText("Cuaca: []");
    LblSuhu.setText("Suhu: []");
    LblKelembapan.setText("Kelembapan: []");
    LblKondisi.setText("Kondisi:");
    }
    private JSONObject getWeatherData(String city) throws IOException {
        String urlString = String.format(
            "https://api.openweathermap.org/data/2.5/weather?q=%s&appid=%s&units=metric&lang=id",
            URLEncoder.encode(city, "UTF-8"), API_KEY
        );
        URL url = new URL(urlString);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");

        BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
        StringBuilder response = new StringBuilder();
        String line;
        while ((line = in.readLine()) != null) {
            response.append(line);
        }
        in.close();

        return new JSONObject(response.toString());
    }
    
    private void updateWeatherIcon(String kondisi) {
        String iconPath = "/img/default.png";

    if (kondisi.contains("cerah")) iconPath = "/img/cerah.png";
    else if (kondisi.contains("awan")) iconPath = "/img/berawan.png";
    else if (kondisi.contains("hujan")) iconPath = "/img/hujan.png";
    else if (kondisi.contains("kabut")) iconPath = "/img/kabut.png";

    // Pastikan gambar ditemukan
    java.net.URL imgURL = getClass().getResource(iconPath);
    if (imgURL != null) {
        ImageIcon icon = new ImageIcon(imgURL);
        // Skala ulang agar pas di area label
        Image scaledImage = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        lblGambar.setIcon(new ImageIcon(scaledImage));
    } else {
        System.err.println("Gagal menemukan ikon: " + iconPath);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelJudul = new javax.swing.JPanel();
        LblJudul = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        LblCari = new javax.swing.JLabel();
        TxtKota = new javax.swing.JTextField();
        BtnCek = new javax.swing.JButton();
        CbxLokasi = new javax.swing.JComboBox<>();
        LblCuaca = new javax.swing.JLabel();
        LblSuhu = new javax.swing.JLabel();
        LblKelembapan = new javax.swing.JLabel();
        LblKondisi = new javax.swing.JLabel();
        BtnSimpanData = new javax.swing.JButton();
        BtnMuatData = new javax.swing.JButton();
        lblGambar = new javax.swing.JLabel();
        BtnSimpan = new javax.swing.JButton();
        PanelTabel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblCuaca = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelJudul.setBackground(new java.awt.Color(51, 102, 255));

        LblJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblJudul.setForeground(new java.awt.Color(255, 255, 255));
        LblJudul.setText("APLIKASI CEK CUACA");

        javax.swing.GroupLayout PanelJudulLayout = new javax.swing.GroupLayout(PanelJudul);
        PanelJudul.setLayout(PanelJudulLayout);
        PanelJudulLayout.setHorizontalGroup(
            PanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJudulLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelJudulLayout.setVerticalGroup(
            PanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJudulLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LblJudul)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PanelInfo.setBackground(new java.awt.Color(51, 51, 255));
        PanelInfo.setForeground(new java.awt.Color(51, 51, 255));

        LblCari.setBackground(new java.awt.Color(255, 255, 255));
        LblCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblCari.setForeground(new java.awt.Color(255, 255, 255));
        LblCari.setText("Cari Kota:");

        TxtKota.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N

        BtnCek.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        BtnCek.setText("Cek");
        BtnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCekActionPerformed(evt);
            }
        });

        CbxLokasi.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N

        LblCuaca.setBackground(new java.awt.Color(255, 255, 255));
        LblCuaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblCuaca.setForeground(new java.awt.Color(255, 255, 255));
        LblCuaca.setText("Cuaca: ");

        LblSuhu.setBackground(new java.awt.Color(255, 255, 255));
        LblSuhu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblSuhu.setForeground(new java.awt.Color(255, 255, 255));
        LblSuhu.setText("Suhu: [ ]");

        LblKelembapan.setBackground(new java.awt.Color(255, 255, 255));
        LblKelembapan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblKelembapan.setForeground(new java.awt.Color(255, 255, 255));
        LblKelembapan.setText("Kelembapan: [ ]");

        LblKondisi.setBackground(new java.awt.Color(255, 255, 255));
        LblKondisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblKondisi.setForeground(new java.awt.Color(255, 255, 255));
        LblKondisi.setText("Kondisi:");

        BtnSimpanData.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        BtnSimpanData.setText("Simpan Data");
        BtnSimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanDataActionPerformed(evt);
            }
        });

        BtnMuatData.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        BtnMuatData.setText("Muat Data");
        BtnMuatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMuatDataActionPerformed(evt);
            }
        });

        lblGambar.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N

        BtnSimpan.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInfoLayout.createSequentialGroup()
                        .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblCari)
                            .addComponent(LblCuaca)
                            .addComponent(LblSuhu)
                            .addComponent(LblKelembapan)
                            .addGroup(PanelInfoLayout.createSequentialGroup()
                                .addComponent(LblKondisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGambar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelInfoLayout.createSequentialGroup()
                        .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoLayout.createSequentialGroup()
                                .addComponent(BtnMuatData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(BtnSimpanData))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoLayout.createSequentialGroup()
                                .addComponent(TxtKota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelInfoLayout.createSequentialGroup()
                                .addComponent(CbxLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoLayout.createSequentialGroup()
                .addComponent(LblCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblCuaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblSuhu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblKelembapan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblKondisi)
                    .addComponent(lblGambar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpanData)
                    .addComponent(BtnMuatData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTabel.setBackground(new java.awt.Color(51, 51, 255));

        TblCuaca.setBackground(new java.awt.Color(153, 153, 255));
        TblCuaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TblCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Area", "Cuaca", "Suhu", "Kelembapan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TblCuaca);

        javax.swing.GroupLayout PanelTabelLayout = new javax.swing.GroupLayout(PanelTabel);
        PanelTabel.setLayout(PanelTabelLayout);
        PanelTabelLayout.setHorizontalGroup(
            PanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelTabelLayout.setVerticalGroup(
            PanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(PanelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelTabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCekActionPerformed
            String city = TxtKota.getText().trim();
    if (city.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu!");
        return;
    }

    try {
        JSONObject data = getWeatherData(city);
        JSONObject main = data.getJSONObject("main");
        JSONObject weather = data.getJSONArray("weather").getJSONObject(0);

        String kondisi = weather.getString("description");
        double suhu = main.getDouble("temp");
        int kelembapan = main.getInt("humidity");

        // Tampilkan hasil ke label
        LblCuaca.setText("Cuaca: " + kondisi);
        LblSuhu.setText("Suhu: " + suhu + "°C");
        LblKelembapan.setText("Kelembapan: " + kelembapan + "%");

        // Menambahkan ke tabel (opsional)
        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) TblCuaca.getModel();
        model.addRow(new Object[]{city, kondisi, suhu + "°C", kelembapan + "%"});
        
        updateWeatherIcon(kondisi);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
    }
    }//GEN-LAST:event_BtnCekActionPerformed

    private void BtnSimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanDataActionPerformed
        simpanDataKeCSV();   
    }//GEN-LAST:event_BtnSimpanDataActionPerformed

    private void BtnMuatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMuatDataActionPerformed
        muatDataDariCSV();
    }//GEN-LAST:event_BtnMuatDataActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
    String kota = TxtKota.getText().trim();
    if (kota.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu!");
        return;
    }

    // Cek apakah kota sudah ada di daftar
    boolean sudahAda = false;
    for (int i = 0; i < CbxLokasi.getItemCount(); i++) {
        if (CbxLokasi.getItemAt(i).equalsIgnoreCase(kota)) {
            sudahAda = true;
            break;
        }
            }

    if (!sudahAda) {
        CbxLokasi.addItem(kota);
        simpanKotaFavorit();
        JOptionPane.showMessageDialog(this, kota + " telah ditambahkan ke daftar favorit!");
    } else {
        JOptionPane.showMessageDialog(this, kota + " sudah ada di daftar favorit.");
    }
    }//GEN-LAST:event_BtnSimpanActionPerformed
    
    private void simpanDataKeCSV() {
    try (PrintWriter writer = new PrintWriter(new File("data_cuaca.csv"))) {
        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) TblCuaca.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            writer.println(
                model.getValueAt(i, 0) + "," +
                model.getValueAt(i, 1) + "," +
                model.getValueAt(i, 2) + "," +
                model.getValueAt(i, 3)
            );
        }
        JOptionPane.showMessageDialog(this, "Data cuaca berhasil disimpan!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
    }
}

private void muatDataDariCSV() {
    try (BufferedReader br = new BufferedReader(new FileReader("data_cuaca.csv"))) {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) TblCuaca.getModel();
        model.setRowCount(0); // Hapus data lama

        String line;
        while ((line = br.readLine()) != null) {
            model.addRow(line.split(","));
        }
        JOptionPane.showMessageDialog(this, "Data berhasil dimuat!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat: " + e.getMessage());
    }
}
// 🔸 Menyimpan daftar kota favorit ke file favorit.txt
private void simpanKotaFavorit() {
    try (PrintWriter writer = new PrintWriter(new FileWriter("favorit.txt"))) {
        for (int i = 0; i < CbxLokasi.getItemCount(); i++) {
            String kota = CbxLokasi.getItemAt(i);
            if (!kota.equals("Pilih Kota")) {
                writer.println(kota);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan favorit: " + e.getMessage());
    }
}

// 🔸 Memuat daftar kota favorit dari file favorit.txt
private void muatKotaFavorit() {
    CbxLokasi.removeAllItems();
    CbxLokasi.addItem("");

    File file = new File("favorit.txt");
    if (!file.exists()) return;

    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line;
        while ((line = br.readLine()) != null) {
            if (!line.trim().isEmpty()) {
                CbxLokasi.addItem(line.trim());
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat daftar favorit: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekCuacaSederhanaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekCuacaSederhanaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekCuacaSederhanaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekCuacaSederhanaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekCuacaSederhanaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCek;
    private javax.swing.JButton BtnMuatData;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnSimpanData;
    private javax.swing.JComboBox<String> CbxLokasi;
    private javax.swing.JLabel LblCari;
    private javax.swing.JLabel LblCuaca;
    private javax.swing.JLabel LblJudul;
    private javax.swing.JLabel LblKelembapan;
    private javax.swing.JLabel LblKondisi;
    private javax.swing.JLabel LblSuhu;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelJudul;
    private javax.swing.JPanel PanelTabel;
    private javax.swing.JTable TblCuaca;
    private javax.swing.JTextField TxtKota;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGambar;
    // End of variables declaration//GEN-END:variables
}
